version: '3'
services:
  processor:
    build:
      dockerfile: Dockerfile.dev
      context: ./processor
    volumes:
      - ./processor:/app
      - /app/bin
    environment:
      - PORT=8082
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
      - /app/bin
    ports:
      - '8081:8081'
    environment:
        - PORT=8081
        - PROCESSOR_ADDRESS=processor:8082