version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'

  processor:
    build:
      dockerfile: Dockerfile.dev
      context: ./processor
    volumes:
      - ./processor:/app
      - /app/bin
    environment:
      - PORT=8081

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
      - /app/bin
    environment:
      - PORT=8080
      - PROCESSOR_ADDRESS=processor:8081

  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app