FROM golang:alpine
WORKDIR '/app'


# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon
COPY . .

CMD CompileDaemon --build="go build -o ./bin/api ." --command="./bin/api"